import { Product, Category, Banner, Coupon } from '../types';

export const INITIAL_CATEGORIES: Category[] = [
  {
    id: 'cold-pressed-oils',
    name: 'Cold Pressed Oils',
    name_telugu: 'కొయ్యగానుగ నూనెలు',
    slug: 'cold-pressed-oils',
    image: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=600&auto=format&fit=crop&q=80',
    sort_order: 1,
    status: 'ACTIVE',
  },
  {
    id: 'groundnut-oil',
    name: 'Groundnut Oil',
    name_telugu: 'వేరుశెనగ నూనె',
    slug: 'groundnut-oil',
    image: 'https://images.unsplash.com/photo-1590779033100-9f60a05a013d?w=600&auto=format&fit=crop&q=80',
    sort_order: 2,
    status: 'ACTIVE',
  },
  {
    id: 'sesame-oil',
    name: 'Sesame Oil',
    name_telugu: 'నువ్వుల నూనె',
    slug: 'sesame-oil',
    image: 'https://images.unsplash.com/photo-1620706857370-e1b9770e8bb1?w=600&auto=format&fit=crop&q=80',
    sort_order: 3,
    status: 'ACTIVE',
  },
  {
    id: 'coconut-oil',
    name: 'Coconut Oil',
    name_telugu: 'కొబ్బరి నూనె',
    slug: 'coconut-oil',
    image: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=600&auto=format&fit=crop&q=80',
    sort_order: 4,
    status: 'ACTIVE',
  },
  {
    id: 'pulses-grains',
    name: 'Pulses & Navaratnalu',
    name_telugu: 'పప్పులు & నవరత్నాలు',
    slug: 'pulses-grains',
    image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=600&auto=format&fit=crop&q=80',
    sort_order: 5,
    status: 'ACTIVE',
  },
  {
    id: 'spices',
    name: 'Spices & Masalas',
    name_telugu: 'మసాలాలు & పోపులు',
    slug: 'spices',
    image: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&auto=format&fit=crop&q=80',
    sort_order: 6,
    status: 'ACTIVE',
  },
  {
    id: 'flours',
    name: 'Stone-Ground Flours',
    name_telugu: 'తిరగలి పిండ్లు',
    slug: 'flours',
    image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=600&auto=format&fit=crop&q=80',
    sort_order: 7,
    status: 'ACTIVE',
  },
  {
    id: 'agro-foods',
    name: 'Agro Foods & Sweeteners',
    name_telugu: 'స్వచ్ఛమైన ఆహార ఉత్పత్తులు',
    slug: 'agro-foods',
    image: 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=600&auto=format&fit=crop&q=80',
    sort_order: 8,
    status: 'ACTIVE',
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-groundnut-oil',
    category_id: 'groundnut-oil',
    name: "Shreshta Traditional Wood Pressed Groundnut Oil",
    name_telugu: "శ్రేష్ట కొయ్యగానుగ వేరుశెనగ నూనె",
    slug: 'wood-pressed-groundnut-oil',
    description: "Extracted using traditional Vaagai wood chekku (cold-press expeller) at gentle low RPM under 35°C to preserve authentic nutty aroma, micro-nutrients, natural antioxidants, and healthy fats. 100% chemical-free and unrefined.",
    highlights: [
      "Traditional Vaagai Wood Pressed (Chekku)",
      "Zero Chemicals, Solvents & Preservatives",
      "Unrefined & Naturally Settled by Sunlight",
      "Rich in Natural Vitamin E & Resveratrol",
      "High Smoke Point - Ideal for Indian Curries & Deep Frying"
    ],
    ingredients: "100% Native Sun-Dried Premium Peanut / Groundnut Kernels.",
    storage_information: "Store in a cool, dry place away from direct sunlight. Reseal cap tightly after each use.",
    delivery_information: "Delivered in food-grade tin or leak-proof bottle within 24-48 hours. Free delivery on orders above ₹799.",
    main_image: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=800&auto=format&fit=crop&q=80",
    status: 'ACTIVE',
    featured: true,
    rating: 4.9,
    reviews_count: 248,
    variants: [
      {
        id: 'var-gn-500ml',
        size: '500 ml',
        unit: 'ml',
        price: 180,
        mrp: 220,
        stock_quantity: 45,
        sku: 'SHR-GNO-500',
        status: 'ACTIVE',
      },
      {
        id: 'var-gn-1L',
        size: '1 Litre',
        unit: 'L',
        price: 340,
        mrp: 400,
        stock_quantity: 120,
        sku: 'SHR-GNO-1000',
        status: 'ACTIVE',
      },
      {
        id: 'var-gn-5L',
        size: '5 Litres (Family Tin)',
        unit: 'L',
        price: 1650,
        mrp: 1950,
        stock_quantity: 35,
        sku: 'SHR-GNO-5000',
        status: 'ACTIVE',
      },
    ],
  },
  {
    id: 'prod-sesame-oil',
    category_id: 'sesame-oil',
    name: "Shreshta Wood Pressed Sesame (Gingelly) Oil",
    name_telugu: "శ్రేష్ట స్వచ్ఛమైన గానుగ నువ్వుల నూనె",
    slug: 'wood-pressed-sesame-oil',
    description: "Prepared from selected native black/brown sesame seeds traditionally blended with pure organic palm jaggery (bellam) in heavy wooden stone chekku. Provides legendary aroma, cooling body balance, and culinary richness.",
    highlights: [
      "Traditional Bellam Nuvvula Nune method",
      "Rich in Sesamol, Sesamolin & Calcium",
      "Ancient Ayurvedic Tridosha Balancing Oil",
      "Unbleached, Unfiltered & Pure Natural Scent",
      "Perfect for Andhra Pickles, Podis & Tadkas"
    ],
    ingredients: "Native Sesame Seeds (Nuvvulu), Organic Palm Jaggery (Bellam).",
    storage_information: "Keep in a dark, dry pantry. Best before 9 months from pressing.",
    delivery_information: "Safely packaged with tamper-evident seal. Next-day delivery available.",
    main_image: "https://images.unsplash.com/photo-1620706857370-e1b9770e8bb1?w=800&auto=format&fit=crop&q=80",
    status: 'ACTIVE',
    featured: true,
    rating: 4.95,
    reviews_count: 189,
    variants: [
      {
        id: 'var-ses-500ml',
        size: '500 ml',
        unit: 'ml',
        price: 240,
        mrp: 290,
        stock_quantity: 30,
        sku: 'SHR-SES-500',
        status: 'ACTIVE',
      },
      {
        id: 'var-ses-1L',
        size: '1 Litre',
        unit: 'L',
        price: 460,
        mrp: 540,
        stock_quantity: 85,
        sku: 'SHR-SES-1000',
        status: 'ACTIVE',
      },
      {
        id: 'var-ses-5L',
        size: '5 Litres (Economy Can)',
        unit: 'L',
        price: 2200,
        mrp: 2600,
        stock_quantity: 20,
        sku: 'SHR-SES-5000',
        status: 'ACTIVE',
      },
    ],
  },
  {
    id: 'prod-coconut-oil',
    category_id: 'coconut-oil',
    name: "Shreshta Extra Virgin Wood Pressed Coconut Oil",
    name_telugu: "శ్రేష్ట స్వచ్ఛమైన గానుగ కొబ్బరి నూనె",
    slug: 'wood-pressed-coconut-oil',
    description: "Pressed from mature, sulphur-free sun-dried Konaseema copra using traditional wooden pestles. Crystal clear when warm, fragrant, multi-purpose oil suitable for edible consumption, baby massage, and hair nourishment.",
    highlights: [
      "100% Pure Edible & Dietary Grade",
      "Rich in Lauric Acid and MCTs",
      "Zero Chemical Bleaching or Refining",
      "Zero Mineral Oil / Paraffin Adulteration",
      "Authentic Coastal Andhra Coconut Flavor"
    ],
    ingredients: "100% Naturally Dried Sulphur-Free Coconut Copra.",
    storage_information: "Solidifies naturally below 24°C without altering purity. Keep in warm water to liquefy.",
    delivery_information: "Directly dispatched from farm mill within 24 hours.",
    main_image: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=800&auto=format&fit=crop&q=80",
    status: 'ACTIVE',
    featured: true,
    rating: 4.88,
    reviews_count: 310,
    variants: [
      {
        id: 'var-coc-500ml',
        size: '500 ml',
        unit: 'ml',
        price: 210,
        mrp: 260,
        stock_quantity: 50,
        sku: 'SHR-COC-500',
        status: 'ACTIVE',
      },
      {
        id: 'var-coc-1L',
        size: '1 Litre',
        unit: 'L',
        price: 390,
        mrp: 470,
        stock_quantity: 90,
        sku: 'SHR-COC-1000',
        status: 'ACTIVE',
      },
      {
        id: 'var-coc-5L',
        size: '5 Litres (Tin Container)',
        unit: 'L',
        price: 1850,
        mrp: 2250,
        stock_quantity: 18,
        sku: 'SHR-COC-5000',
        status: 'ACTIVE',
      },
    ],
  },
  {
    id: 'prod-navaratnalu-kit',
    category_id: 'pulses-grains',
    name: "Shreshta Navaratnalu 9-Sacred Grains Family Kit",
    name_telugu: "నవరత్నాలు - సంప్రదాయ 9 ధాన్యాల ఫ్యామిలీ కిట్ (10+ KG)",
    slug: 'navaratnalu-family-essentials-kit',
    description: "The complete monthly staple kit consolidating 9 sacred, nutrient-dense native grains & pulses: Toor dal (కందులు), Moong (పెసలు), Urad (మినుములు), Bengal gram (శనగలు), Sesame (నువ్వులు), Bansi Wheat (గోధుమలు), Hand-pounded Rice (వరి), Horsegram (ఉలువలు), and Cowpeas (బొబ్బర్లు). Meets the monthly wholesome nutrition for a 4-person family.",
    highlights: [
      "Complete 9 Sacred Grains in 1 Curated Kit",
      "Native Heirloom Seeds, Non-GMO & Unpolished",
      "Zero Chemical Polish, Zero Added Artificial Powder",
      "Packed in Eco-Friendly Breathable Cotton/Jute Sacks",
      "Customizable Monthly Delivery Schedule"
    ],
    ingredients: "Toor Dal (2kg), Moong Dal (1kg), Black Urad (2kg), Brown Chana (1kg), White Sesame (500g), Whole Wheat (2kg), Hand-Pounded Brown Rice (2kg), Horsegram (500g), Cowpeas (500g).",
    storage_information: "Store in airtight containers or traditional brass/steel bins in a dry pantry.",
    delivery_information: "Dispatched in sturdy multi-layer carton box with individual grain packets.",
    main_image: "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=800&auto=format&fit=crop&q=80",
    status: 'ACTIVE',
    featured: true,
    rating: 4.98,
    reviews_count: 412,
    variants: [
      {
        id: 'var-nav-10kg',
        size: '10+ KG Monthly Essential Kit',
        unit: 'Kg',
        price: 1550,
        mrp: 1850,
        stock_quantity: 40,
        sku: 'SHR-NAV-10KG',
        status: 'ACTIVE',
      },
      {
        id: 'var-nav-15kg',
        size: '15 KG Large Family Mega Kit',
        unit: 'Kg',
        price: 2250,
        mrp: 2700,
        stock_quantity: 25,
        sku: 'SHR-NAV-15KG',
        status: 'ACTIVE',
      },
    ],
  },
  {
    id: 'prod-deepam-oil',
    category_id: 'cold-pressed-oils',
    name: "Shreshta Pancha Deepam Pooja Oil (Divine Puja Blend)",
    name_telugu: "శ్రేష్ట పంచ దీపారాధన తైలం (5 పవిత్ర నూనెలు)",
    slug: 'pancha-deepam-pooja-oil',
    description: "Handcrafted according to Agama Shastra specifications by blending 5 sacred oils: Pure Sesame Oil, Mahua Oil (Ippa Nune), Castor Oil (Aamudam), Neem Oil (Vepa Nune), and Pure Cow Ghee with mild Camphor aroma. Cleanses positive aura and gives a long-lasting sootless flame.",
    highlights: [
      "Traditional 5-Oil Blend for Puja & Mandir",
      "Infused with Pure Sugandha Dravyas",
      "Clean Burning with Minimal Soot",
      "Promotes Peace, Prosperity and Positive Energy",
      "Formulated Strictly According to Traditional Texts"
    ],
    ingredients: "Sesame Oil (35%), Mahua Oil (25%), Castor Oil (20%), Neem Oil (10%), Cow Ghee (10%), Natural Sugandha herbs.",
    storage_information: "Store near puja room away from open flames.",
    delivery_information: "Packed in sturdy spill-safe container.",
    main_image: "https://images.unsplash.com/photo-1590779033100-9f60a05a013d?w=800&auto=format&fit=crop&q=80",
    status: 'ACTIVE',
    featured: false,
    rating: 4.92,
    reviews_count: 145,
    variants: [
      {
        id: 'var-deep-1L',
        size: '1 Litre',
        unit: 'L',
        price: 290,
        mrp: 350,
        stock_quantity: 60,
        sku: 'SHR-DEEP-1000',
        status: 'ACTIVE',
      },
      {
        id: 'var-deep-2L',
        size: '2 Litres Bottle',
        unit: 'L',
        price: 550,
        mrp: 680,
        stock_quantity: 35,
        sku: 'SHR-DEEP-2000',
        status: 'ACTIVE',
      },
    ],
  },
  {
    id: 'prod-toor-dal',
    category_id: 'pulses-grains',
    name: "Shreshta Desi Unpolished Toor Dal (Native Kandi Pappu)",
    name_telugu: "శ్రేష్ట దేశవాళీ పొట్టు తీయని కందిపప్పు",
    slug: 'unpolished-desi-toor-dal',
    description: "Farm-harvested native heirloom toor dal directly from rainfed black soil farms. Naturally dried in the sun, stone dehusked with no artificial water or oil polish, locking in deep natural protein flavor and easy digestibility.",
    highlights: [
      "100% Unpolished & Non-GMO",
      "Cooks into Creamy, Rich Traditional Pappu / Sambar",
      "High Protein, Dietary Fiber & Folate",
      "No Chemical Wax or Water Tumbling"
    ],
    ingredients: "100% Native Dried Pigeon Pea (Kandi Pappu).",
    storage_information: "Store in a clean airtight container with 1-2 neem leaves for natural preservation.",
    delivery_information: "Dispatched in hygienic ziplock pouch.",
    main_image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800&auto=format&fit=crop&q=80",
    status: 'ACTIVE',
    featured: false,
    rating: 4.86,
    reviews_count: 172,
    variants: [
      {
        id: 'var-td-1kg',
        size: '1 Kg',
        unit: 'Kg',
        price: 190,
        mrp: 230,
        stock_quantity: 80,
        sku: 'SHR-TD-1KG',
        status: 'ACTIVE',
      },
      {
        id: 'var-td-2kg',
        size: '2 Kg Pack',
        unit: 'Kg',
        price: 370,
        mrp: 450,
        stock_quantity: 40,
        sku: 'SHR-TD-2KG',
        status: 'ACTIVE',
      },
    ],
  },
  {
    id: 'prod-guntur-chilli',
    category_id: 'spices',
    name: "Shreshta Andhra Guntur Teja Chilli Powder",
    name_telugu: "గుంటూరు తేజ స్వచ్ఛమైన కారం పొడి",
    slug: 'guntur-teja-chilli-powder',
    description: "Sun-dried selected Guntur Teja chillies, stem-removed, traditionally pounded on slow hammer mills to prevent scorching. Delivers vibrant natural crimson color, robust pungent heat, and tantalizing aroma with zero added dyes.",
    highlights: [
      "Stemless Handpicked Guntur Teja Chillies",
      "No Added Colors (Sudan dye free), No Sawdust",
      "Slow Pounded to Retain Essential Capsaicin Oils",
      "Authentic Spicy Andhra Taste Guaranteed"
    ],
    ingredients: "100% Stemless Pure Guntur Red Chillies.",
    storage_information: "Keep in dry container. Use dry spoon.",
    delivery_information: "Standard 2-day delivery across Andhra, Telangana & South India.",
    main_image: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=800&auto=format&fit=crop&q=80",
    status: 'ACTIVE',
    featured: false,
    rating: 4.94,
    reviews_count: 220,
    variants: [
      {
        id: 'var-ch-500g',
        size: '500 g',
        unit: 'g',
        price: 180,
        mrp: 220,
        stock_quantity: 75,
        sku: 'SHR-CHI-500',
        status: 'ACTIVE',
      },
      {
        id: 'var-ch-1kg',
        size: '1 Kg Value Pack',
        unit: 'Kg',
        price: 350,
        mrp: 420,
        stock_quantity: 50,
        sku: 'SHR-CHI-1000',
        status: 'ACTIVE',
      },
    ],
  },
  {
    id: 'prod-salem-turmeric',
    category_id: 'spices',
    name: "Shreshta Stone Ground Salem Turmeric Powder",
    name_telugu: "పసుపు కొమ్ముల పొడి (5%+ కర్క్యుమిన్)",
    slug: 'stone-ground-salem-turmeric',
    description: "Grown in nutrient-rich soils and harvested at peak potency. Boiled, cured, sun-dried, and finely powdered on cool stone mills. Lab tested with >5% Curcumin for maximum anti-inflammatory benefits and golden warmth.",
    highlights: [
      "Guaranteed High Curcumin (>5%)",
      "Zero Lead Chromate or Artificial Yellow Dyes",
      "Healing Ayurvedic Grade & Immunity Booster",
      "Earthy Natural Fragrance"
    ],
    ingredients: "100% Pure Cured Turmeric Finger Rhizomes (Pasupu Kommulu).",
    storage_information: "Keep away from moisture in airtight jar.",
    delivery_information: "Delivered in moisture-barrier container.",
    main_image: "https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=800&auto=format&fit=crop&q=80",
    status: 'ACTIVE',
    featured: false,
    rating: 4.97,
    reviews_count: 165,
    variants: [
      {
        id: 'var-tur-250g',
        size: '250 g',
        unit: 'g',
        price: 110,
        mrp: 140,
        stock_quantity: 90,
        sku: 'SHR-TUR-250',
        status: 'ACTIVE',
      },
      {
        id: 'var-tur-500g',
        size: '500 g',
        unit: 'g',
        price: 200,
        mrp: 260,
        stock_quantity: 65,
        sku: 'SHR-TUR-500',
        status: 'ACTIVE',
      },
    ],
  },
  {
    id: 'prod-bansi-atta',
    category_id: 'flours',
    name: "Shreshta Stone Chakki Ground Bansi Wheat Atta",
    name_telugu: "రాయి తిరగలి గోధుమ పిండి (ఫైబర్ పుష్కలం)",
    slug: 'stone-chakki-wheat-atta',
    description: "Crafted from hard Bansi amber wheat grains ground at low speeds on natural granite millstones. Unlike commercial high-heat steel rollers, stone milling prevents nutrient degradation and keeps rotis soft for hours without additives.",
    highlights: [
      "100% Whole Wheat with Intact Bran & Germ",
      "Low-RPM Cool Stone Chakki Milled",
      "Zero Maida / Starch Adulteration",
      "Rotis Stay Tender & Fluffy All Day"
    ],
    ingredients: "100% Native Bansi Whole Wheat Grain.",
    storage_information: "Store in cool container. Best consumed within 60 days of milling for freshest taste.",
    delivery_information: "Freshly milled batch shipped directly to your door.",
    main_image: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=800&auto=format&fit=crop&q=80",
    status: 'ACTIVE',
    featured: false,
    rating: 4.89,
    reviews_count: 198,
    variants: [
      {
        id: 'var-att-5kg',
        size: '5 Kg Bag',
        unit: 'Kg',
        price: 280,
        mrp: 340,
        stock_quantity: 45,
        sku: 'SHR-ATT-5000',
        status: 'ACTIVE',
      },
    ],
  },
  {
    id: 'prod-organic-jaggery',
    category_id: 'agro-foods',
    name: "Shreshta Farm-Fresh Organic Jaggery Powder (Bellam)",
    name_telugu: "స్వచ్ఛమైన సేంద్రీయ బెల్లం పొడి",
    slug: 'organic-jaggery-powder',
    description: "Directly crushed from freshly harvested Konaseema organic sugarcane juice and boiled in traditional iron pans using wild herbal clarifiers. Unbleached, naturally dark golden, rich in iron, minerals, and comforting sweetness.",
    highlights: [
      "No Chemical Clarifiers or Sodium Hydrosulphite",
      "Rich in Natural Iron & Dietary Minerals",
      "Ready-to-Use Fine Granular Powder",
      "Ideal for Milk, Payasam, Tea & Sweet Preparations"
    ],
    ingredients: "100% Pure Organic Sugarcane Juice.",
    storage_information: "Keep in cool, dry place. Seal zip tightly.",
    delivery_information: "Available for standard delivery.",
    main_image: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=800&auto=format&fit=crop&q=80",
    status: 'ACTIVE',
    featured: false,
    rating: 4.91,
    reviews_count: 134,
    variants: [
      {
        id: 'var-jag-1kg',
        size: '1 Kg Ziplock',
        unit: 'Kg',
        price: 120,
        mrp: 150,
        stock_quantity: 60,
        sku: 'SHR-JAG-1000',
        status: 'ACTIVE',
      },
    ],
  },
];

export const INITIAL_BANNERS: Banner[] = [
  {
    id: 'banner-1',
    title: "100% Pure Cold Pressed Oils",
    subtitle: "Extracted gently in traditional Vaagai wood chekku below 35°C",
    highlight: "BORN TO ADD VALUE",
    image: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=1200&auto=format&fit=crop&q=80",
    action_url: "/products?category=cold-pressed-oils",
    active: true,
    sort_order: 1,
  },
  {
    id: 'banner-2',
    title: "Monthly Family Essentials Kit",
    subtitle: "10+ KG Navaratnalu Sacred Grains + 5 KG Cold-Pressed Oils delivered to your doorstep",
    highlight: "SAVE UP TO 25% ON SUBSCRIPTION",
    image: "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=1200&auto=format&fit=crop&q=80",
    action_url: "/subscription",
    active: true,
    sort_order: 2,
  },
  {
    id: 'banner-3',
    title: "Traditional Andhra Harvest Spices",
    subtitle: "Stone-pounded Guntur Teja chillies and high-curcumin Salem turmeric",
    highlight: "FARM DIRECT PURE AGRO",
    image: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=1200&auto=format&fit=crop&q=80",
    action_url: "/products?category=spices",
    active: true,
    sort_order: 3,
  },
];

export const INITIAL_COUPONS: Coupon[] = [
  {
    id: 'coupon-shreshta100',
    code: 'SHRESHTA100',
    title: 'Flat ₹100 Off on First Order',
    discount_type: 'FIXED',
    discount_value: 100,
    minimum_order: 599,
    maximum_discount: 100,
    start_date: '2025-01-01',
    end_date: '2028-12-31',
    usage_limit: 10000,
    per_user_limit: 1,
    status: 'ACTIVE',
  },
  {
    id: 'coupon-welcome50',
    code: 'WELCOME50',
    title: 'Flat ₹50 Off for New Customers',
    discount_type: 'FIXED',
    discount_value: 50,
    minimum_order: 350,
    maximum_discount: 50,
    start_date: '2025-01-01',
    end_date: '2028-12-31',
    usage_limit: 5000,
    per_user_limit: 1,
    status: 'ACTIVE',
  },
  {
    id: 'coupon-healthy10',
    code: 'HEALTHY10',
    title: '10% Discount on Bulk Orders',
    discount_type: 'PERCENTAGE',
    discount_value: 10,
    minimum_order: 1200,
    maximum_discount: 300,
    start_date: '2025-01-01',
    end_date: '2028-12-31',
    usage_limit: 5000,
    per_user_limit: 3,
    status: 'ACTIVE',
  },
];
